### ISSUE TITLE
bug: a lot of visual issues

### ISSUE THREAD

**Issue by lino-levan** [cookiedb/docs.cookiedb.com#9]
There are a ton of visual bugs with the current iteration of docs. Noting these here as I find them

- [x] If articles don't contain a lot of text, everything is squished. See https://docs.cookiedb.com/docs/admin-api/create-user #11
- [x] The dropdown box isn't filled by default. We should fill it with typescript by default. #10
- [ ] There's a whole host of issues with search
  - [x] Searching a common expression (like "cookie") breaks the search box. We should limit it to the top 5 most relevant results. #10
  - [ ] In articles bigger than a page, the user can scroll away from the search box.
